<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RuntimeFrameworkVersion>8.0.0</RuntimeFrameworkVersion>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="settings.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.DotMemoryUnit" Version="3.2.20220510" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DiscordBotsList.Api\DiscordBotsList.Api.csproj" />
        <EmbeddedResource Include="mocks\*.json" />
    </ItemGroup>

</Project>
